version: "3"

services:
  backend:
    build: ./
    container_name: nestback
    restart: always
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql_db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
